version: '3'


services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: todoapp
    restart: always
    env_file: .env
    volumes:
      - .:/todoapp
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - postgres # says that we should start the postgres first before running our web services.
      - redis # added
      - celery

  postgres:
    container_name:  todoapp-postgres-db
    image:           postgres:9.6.6
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  redis:
    image: redis:4.0.11
    restart: "on-failure"
    container_name: redis
    ports:
      - 6380:6379
##    volumes:
##      - ./redisdb:/var/lib/redis

  celery:
    build: .
    restart: always
    command: celery -A todoapp worker --loglevel=info
    volumes:
      - .:/todoapp
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis
